### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sebastian444** [mathieutu/vue-cli-plugin-express#14] opened 2019-03-29 08:14 UTC
Hello,

I had to uninstall the plugin and then install it again, and I am getting 

vue-cli-plugin-express@1.0.0
updated 1 package in 12.366s
✔  Successfully installed plugin: vue-cli-plugin-express

 ERROR  ReferenceError: 0 is not defined
/Users/sebastian.lara/.nvm/versions/node/v9.3.0/lib/node_modules/@vue/cli/node_modules/rxjs/internal/util/subscribeToArray.js:5

Do you happen to know why is this?

**Comment by sebastian444** [comment] 2019-03-29 08:16
only the plugin dependency gets added, but all other stuff that should happen afterward( like creating/editing files ) is failing.

**Comment by n3ps** [comment] 2019-04-03 03:52
Same error here and this was working a week ago.

**Comment by valisjan** [comment] 2019-04-06 10:03
Same here...

**Comment by dennis2k** [comment] 2019-04-09 09:53
Same issue here

**Comment by bonesoul** [comment] 2019-04-11 14:13
same..

**Comment by soracoder** [comment] 2019-04-17 09:51
Something on this?

**Comment by dylanbaxter** [comment] 2019-04-17 22:52
I heard there would be cake, but I got this error instead.

**Comment by mdinat3** [comment] 2019-04-18 05:52
I get the same thing, vue 3.5.5, npm 6.9.0 can't use express at all. Just making a separate project to make the api.

**Comment by sunzongzheng** [comment] 2019-04-19 04:32
same here

**Comment by mdinat3** [comment] 2019-04-19 04:33
I ended up just using the standard express npm install express --save that works just fine

**Comment by abbrechen** [comment] 2019-04-24 12:13
Same problem. I get the error `ReferenceError: 0 is not defined` and nothing works.

**Comment by dylanbaxter** [comment] 2019-04-24 14:50
Anyone looking for a work-around might consider this article:
https://dennisreimann.de/articles/vue-cli-serve-express.html

**Comment by krogla** [comment] 2019-04-25 10:11
+1 same problem

**Comment by mathieutu** [comment] 2019-04-27 21:00
Hi folks, I'm just seeing this issue. Sorry, but I should really have a problem with github notifications.

I think this is because some Vue CLI api changes, because last time I used the plugin, it worked perfectly.

I'm trying to fix that right now.

**Comment by mathieutu** [comment] 2019-04-27 22:16
Hi. As I said previously, I've quickly investigate, and found that this issue is linked with https://github.com/standard-things/esm/issues/782.

I've just deployed a new released which fix temporarily the package version, until the problem is handled on their side.

Thanks to all of you for your feedback on this, and sorry again for not having seen this one.

Could you please retry, and confirm me that this is ok for you?

**Comment by soracoder** [comment] 2019-04-29 06:53
Now works fine for me.
Thanks!

**Comment by mathieutu** [comment] 2019-04-29 08:25
Perfect! Closing it.

**Closed by mathieutu** 2019-04-29 08:25 UTC
Labels: needs more info
